apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking
  labels:
    app: booking
spec:
  replicas: 3
  selector:
    matchLabels:
      app: booking
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: booking
    spec:
      containers:
        - name: doctor-appointment-booking-v4
          image: doctor-appointment-booking:v4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80