@url = http://localhost:5001

###
GET {{url}}

###
POST {{url}}/doctortimeslots/create
Content-Type: application/json

{
    "Id": "3ac82ce2-49dc-4b2a-b586-6532b99e2ea1",
    "Time": "2023-02-24T16:30:00",
    "DoctorId": "d63b3de0-8bde-45f5-808b-73042ee6bb0d",
    "DoctorName": "John Smith",
    "IsReserved": true,
    "Cost": 350
}

### 
# @name getTimeSlotsByDoctorId
GET {{url}}/doctortimeslots/d63b3de0-8bde-45f5-808b-73042ee6bb0d

### 
# @name getAvailableSlots
GET {{url}}/doctortimeslots/available HTTP/1.1

###
POST {{url}}/appointments
Content-Type: application/json

{
    "Id": "391c9281-83d4-4a56-b948-b25fecc94270",
    "SlotId": "60d4427c-b956-4393-b186-f61afbbc79ed",
    "PatientId": "74cc2acc-4a55-4208-904a-5ee090239f33",
    "PatientName": "Bob Johnson",
    "ReservedAt": "2023-01-31T09:00:00"
}